### ISSUE TITLE
Script choosing order logic for TokenScript Tlink  

### ISSUE THREAD

**Issue by zhangzhongnan928** [TokenScript-Framework/token-kit#22]
Script choosing logic for TokenScript Tlink   
applys to telegram, open graph and Tlink extension, wallets and any other TokenScript Tlink rendering places.

If user chose a script to use, like &scriptId=7738_2, then use the one in &scriptId=7738_2
https://viewer.tokenscript.org/?chain=137&contract=0xB48f53010Acbc0E24D3D12D892E2215879e6fD13&scriptId=7738_2&tokenId=9002

if user didn't choose any script then, use the value in ERC5169 if exist, otherwise use the value in 7738.

1. use entry id 7738_2 if exist
2. use value in 5169
3. use value in 7738 if no entry id

**Comment by futantan** [comment]
will be fixed in https://github.com/AlphaWallet/common-api/pull/28

**Comment by futantan** [comment]
fixed
