### ISSUE TITLE
Drop down not supported?

### ISSUE THREAD

**Issue by Willisplayed** [TokenScript-Framework/token-kit#26]
Drop down not supported?

> > _Originally posted by @Willisplayed in https://github.com/TokenScript-Framework/token-kit/issues/25 
Ineedhelp

**Comment by foxgem** [comment]
this is not in the plan because shadcn has it already: https://ui.shadcn.com/docs/components/dropdown-menu. the ui components in token-kit are mainly for token related functions.

could you provide more details on your issue?
